FROM scratch

LABEL org.opencontainers.image.title="Mobocker" \
      org.opencontainers.image.description="The dummest container, is the smaller running container to keep Docker daemon alive." \
      org.opencontainers.image.vendor="Oleksis Fraga" \
      io.podman-desktop.api.version=">= 0.12.0"

COPY package.json /extension/
COPY docker.svg /extension/icon.png
# COPY README.md /extension/
COPY dist /extension/dist
